const Map language0 = {
  "report": "ሪፖርት",
  "home": "መነሸ ገጽ",
  "selfTesting": "ግለ-ምርመራ",
  "updateCovidInfo": "አዲስ መረጃ",
  "frequentlyAskedQuestion": "ተደጋጋሚ ጥያቄዎች",
  "help": "እገዛ",
  "about": "ስለ እኛ",
  "exit": "ውጣ",
  "covid19Test": "የኮሮና ምርመራ",
  "name": "ስም",
  "yourAnswer": "መልስ",
  "phoneNumber": "ስልክ ቁጥር",
  "address": "አድራሻ",
  "doYouHaveHighFever": "ከፍተኛ የሙቀት ስሜት አለዎት?",
  "yes": "አዎ",
  "no": "አይ",
  "doYouHaveDryCough": "የሳል ምልክት አለዎት?",
  "didBreathingProblemHappened": "የመተንፈስ ችግር አጋጥሞታል?",
  "didYouGetTired": "የድካም ስሜት ይሰማዎታል?",
  "doYouHaveStomachake": "የሆድ ቁርጠት ስሜት አለዎት?",
  "doYouHaveTravelHistory": "የጉዞ ታሪክ አለዎት?",
  "doYouHaveContactWithUnhelthy": "ከታማሚ ሰው ጋር ንክኪ ነበሮት?",
  "people": "ሕዝብ",
  "covid19Info": "የኮሮና መረጃ",
  "global": "አለም አቀፋዊ",
  "local": "የሀገር ውስጥ",
  "faq": "የብዙሀን ጥያቄ",
  "welcome": "እንኳን ደህና መጡ!!",
  "submit": "ያስገቡ",
  "fatherName": "የአባት ስም",
  "gFatherName": "የአያት ስም",
  "bluetoothName": "የብሉቱዝ ስም",
  "bluetoothAdress": "የብሉቱዝ አድራሻ",
  "register": "መዝግብ"
};
const Map language1 = {
  "report": "Gabaasa",
  "home": "Mana",
  "selfTesting": "Qorannoo Dhuunfaa",
  "updateCovidInfo": "Odeeffannoo haaraa",
  "frequentlyAskedQuestion": "Gsaffiiwwan irradeddeebi'an",
  "help": "Gargaarsa",
  "about": "Waa'ee",
  "exit": "Bahuumsa",
  "covid19Test": "Qorannoo Covid 19",
  "name": "Maqaa",
  "yourAnswer": "Deebii",
  "phoneNumber": "Lakkoofsa Bilbilaa",
  "address": "Iddoo Jireenya",
  "doYouHaveHighFever": "Ho'aa qaama ol ka'aa namatti dhagahamuu?",
  "yes": "Eshii",
  "no": "Lakkii",
  "doYouHaveDryCough": "Utaalloo gogaa?",
  "didBreathingProblemHappened": "Rakkoo hargaanuu sii mudaateera?",
  "didYouGetTired": "Dadhabbiin sitti dhagahamaa?",
  "doYouHaveStomachake": "Garaa ciniinnaa qabdaa?",
  "doYouHaveTravelHistory": "Deemsa karaa fagoo irra turtee?",
  "doYouHaveContactWithUnhelthy":
      "Nama Dhukkubsataataana wal xuxxuqqii qabdaa?",
  "people": "Namoota",
  "covid19Info": "Odeeffannoo Covid 19",
  "global": "Adunyaawwaa",
  "local": "Kan Biyyaa Keessaa",
  "faq": "Gaaffii Namoota Baay'ee",
  "welcome": "Baga Nagaan Dhuftan!!",
  "submit": "Kan Galchuu",
  "fatherName": "Maqaa Abbaa",
  "gFatherName": "Maqaa Akkoo",
  "bluetoothName": "Maqaa Bluetooth",
  "bluetoothAdress": "Bluetooth Address",
  "register": "Galmeessuu",
};
const Map language2 = {
  "report": "Report",
  "home": "Home",
  "selfTesting": "Self Testing",
  "updateCovidInfo": "Update Covid info",
  "frequentlyAskedQuestion": "Frequently Asked Question",
  "help": "Help",
  "about": "About",
  "exit": "Exit",
  "covid19Test": "Covid 19 Test",
  "name": "Name",
  "yourAnswer": "Your Answer",
  "phoneNumber": "Phone Number",
  "address": "Address",
  "doYouHaveHighFever": "Do You Have High Fever?",
  "yes": "Yes",
  "no": "No",
  "doYouHaveDryCough": "Do You Have Dry Cough?",
  "didBreathingProblemHappened": "Did Breathing Problem Happened?",
  "didYouGetTired": "Did You Get Tired?",
  "doYouHaveStomachake": "Do You Have Stomach ace?",
  "doYouHaveTravelHistory": "Do You Have Travel History?",
  "doYouHaveContactWithUnhelthy": "Do You Have Contact With Unhealthy?",
  "people": "People",
  "covid19Info": "Covid 19 info",
  "global": "Global",
  "local": "Local",
  "faq": "FAQ",
  "welcome": "Welcome!!",
  "submit": "Submit",
  "fatherName": "Father Name",
  "gFatherName": "Grand Father Name",
  "bluetoothName": "Bluetooth Name",
  "bluetoothAdress": "Bluetooth Address",
  "register": "Register"
};
const List languageAll = [language0, language1, language2];
